#!/bin/bash
# kubectl-magic-pods - 增强版 Pod 查询插件

set -e

if [ $# -lt 1 ]; then
  echo "用法: kubectl magic pods NAMESPACE [-选项]"
  exit 1
fi

ns="$1"
shift

# 将剩余的所有参数传递给 kubectl get pods 命令
kubectl get pods -n "$ns" "$@"
