#!/bin/bash
# kubectl-magic-pods - 增强版 Pod 查询插件

set -e

if [ $# -lt 1 ]; then
  echo "用法: kubectl magic pods NAMESPACE [-w]"
  exit 1
fi

ns="$1"
shift
watch_flag=""

while getopts ":w" opt; do
  case $opt in
    w) watch_flag="-w";;
    \?) echo "无效选项: -$OPTARG" >&2; exit 1;;
  esac
done

kubectl get pods -n "$ns" $watch_flag 